# Generated by Django 4.1.3 on 2023-01-08 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empire', '0002_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='price',
            new_name='age',
        ),
        migrations.AddField(
            model_name='stock',
            name='number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
