# Generated by Django 4.1.3 on 2023-04-23 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empire', '0005_breeds'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Breeds',
            new_name='RBreeds',
        ),
    ]
