# Generated by Django 4.1.3 on 2023-04-25 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empire', '0006_rename_breeds_rbreeds'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RBreeds',
            new_name='RBreed',
        ),
    ]
